var simplemaps_worldmap_mapdata={
  main_settings: {
    width: "responsive",
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    popups: "detect",
    state_description: "State description",
    state_color: "#dee6f3",
    state_hover_color: "#ffc0cb",
    state_url: "https://www.metliner.com/",
    border_size: "1",
    all_states_inactive: "no",
    all_states_zoomable: "no",
    location_description: "Location description",
    // ── Pin style: small circle, deep terracotta ──
    location_color: "#B84A3E",
    location_opacity: 0.9,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 9,
    location_type: "circle",
    location_border_color: "#FFFFFF",
    location_border: 1.5,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",
    label_color: "#d5ddec",
    label_hover_color: "#d5ddec",
    label_size: 22,
    label_font: "Arial",
    hide_labels: "no",
    zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",   // intercepted by window.open override in index.html
    images_directory: "default",
    fade_time: 0.1,
    link_text: "View Website",
    state_image_url: "",
    state_image_position: "",
    location_image_url: ""
  },
  state_specific: {
    AF:{name:"Afghanistan",color:"#e9dcc9",description:"0 cities"},
    AO:{name:"Angola",color:"#cfbeb4",description:"0 cities"},
    AL:{name:"Albania",color:"#b1b6ba",description:"0 cities"},
    AE:{name:"United Arab Emirates",color:"#82ac7c",description:"1 city"},
    AR:{name:"Argentina",color:"#bfd2c6",description:"0 cities"},
    AM:{name:"Armenia",color:"#7297a0",description:"0 cities"},
    AU:{name:"Australia",color:"#8d9daf",description:"2 cities"},
    AT:{name:"Austria",color:"#b8d0cd",description:"1 city"},
    AZ:{name:"Azerbaijan",color:"#b48c8a",description:"0 cities"},
    BI:{name:"Burundi",color:"#d0b1a3",description:"0 cities"},
    BE:{name:"Belgium",color:"#a88c7d",description:"0 cities"},
    BJ:{name:"Benin",color:"#a493b7",description:"0 cities"},
    BF:{name:"Burkina Faso",color:"#a089a0",description:"0 cities"},
    BD:{name:"Bangladesh",color:"#6d6e80",description:"0 cities"},
    BG:{name:"Bulgaria",color:"#e9dcc9",description:"0 cities"},
    BH:{name:"Bahrain",color:"#cfbeb4",description:"0 cities"},
    BA:{name:"Bosnia and Herzegovina",color:"#b1b6ba",description:"0 cities"},
    BY:{name:"Belarus",color:"#82ac7c",description:"0 cities"},
    BZ:{name:"Belize",color:"#bfd2c6",description:"0 cities"},
    BO:{name:"Bolivia",color:"#7297a0",description:"0 cities"},
    BR:{name:"Brazil",color:"#8d9daf",description:"1 city"},
    BN:{name:"Brunei Darussalam",color:"#b8d0cd",description:"0 cities"},
    BT:{name:"Bhutan",color:"#b48c8a",description:"0 cities"},
    BW:{name:"Botswana",color:"#d0b1a3",description:"0 cities"},
    CF:{name:"Central African Republic",color:"#a88c7d",description:"0 cities"},
    CA:{name:"Canada",color:"#a493b7",description:"6 cities"},
    CH:{name:"Switzerland",color:"#a089a0",description:"0 cities"},
    CL:{name:"Chile",color:"#6d6e80",description:"0 cities"},
    CN:{name:"China",color:"#e9dcc9",description:"9 cities"},
    CI:{name:"Côte d'Ivoire",color:"#cfbeb4",description:"0 cities"},
    CM:{name:"Cameroon",color:"#b1b6ba",description:"0 cities"},
    CD:{name:"Democratic Republic of the Congo",color:"#82ac7c",description:"0 cities"},
    CG:{name:"Republic of Congo",color:"#bfd2c6",description:"0 cities"},
    CO:{name:"Colombia",color:"#7297a0",description:"0 cities"},
    CR:{name:"Costa Rica",color:"#8d9daf",description:"0 cities"},
    CU:{name:"Cuba",color:"#b8d0cd",description:"0 cities"},
    CZ:{name:"Czech Republic",color:"#b48c8a",description:"0 cities"},
    DE:{name:"Germany",color:"#d0b1a3",description:"1 city"},
    DJ:{name:"Djibouti",color:"#a88c7d",description:"0 cities"},
    DK:{name:"Denmark",color:"#a493b7",description:"1 city"},
    DO:{name:"Dominican Republic",color:"#a089a0",description:"0 cities"},
    DZ:{name:"Algeria",color:"#6d6e80",description:"0 cities"},
    EC:{name:"Ecuador",color:"#e9dcc9",description:"0 cities"},
    EG:{name:"Egypt",color:"#cfbeb4",description:"0 cities"},
    ER:{name:"Eritrea",color:"#b1b6ba",description:"0 cities"},
    EE:{name:"Estonia",color:"#82ac7c",description:"0 cities"},
    ET:{name:"Ethiopia",color:"#bfd2c6",description:"0 cities"},
    FI:{name:"Finland",color:"#7297a0",description:"0 cities"},
    FJ:{name:"Fiji",color:"#8d9daf",description:"0 cities"},
    GA:{name:"Gabon",color:"#b8d0cd",description:"0 cities"},
    GB:{name:"United Kingdom",color:"#b48c8a",description:"1 city"},
    GE:{name:"Georgia",color:"#d0b1a3",description:"0 cities"},
    GH:{name:"Ghana",color:"#a88c7d",description:"0 cities"},
    GN:{name:"Guinea",color:"#a493b7",description:"0 cities"},
    GM:{name:"The Gambia",color:"#a089a0",description:"0 cities"},
    GW:{name:"Guinea-Bissau",color:"#6d6e80",description:"0 cities"},
    GQ:{name:"Equatorial Guinea",color:"#e9dcc9",description:"0 cities"},
    GR:{name:"Greece",color:"#cfbeb4",description:"0 cities"},
    GL:{name:"Greenland",color:"#b1b6ba",description:"0 cities"},
    GT:{name:"Guatemala",color:"#82ac7c",description:"0 cities"},
    GY:{name:"Guyana",color:"#bfd2c6",description:"0 cities"},
    HN:{name:"Honduras",color:"#7297a0",description:"0 cities"},
    HR:{name:"Croatia",color:"#8d9daf",description:"0 cities"},
    HT:{name:"Haiti",color:"#b8d0cd",description:"0 cities"},
    HU:{name:"Hungary",color:"#b48c8a",description:"0 cities"},
    ID:{name:"Indonesia",color:"#d0b1a3",description:"1 city"},
    IN:{name:"India",color:"#a88c7d",description:"0 cities"},
    IE:{name:"Ireland",color:"#a493b7",description:"0 cities"},
    IR:{name:"Iran",color:"#a089a0",description:"0 cities"},
    IQ:{name:"Iraq",color:"#6d6e80",description:"0 cities"},
    IS:{name:"Iceland",color:"#e9dcc9",description:"0 cities"},
    IL:{name:"Israel",color:"#cfbeb4",description:"0 cities"},
    IT:{name:"Italy",color:"#b1b6ba",description:"0 cities"},
    JM:{name:"Jamaica",color:"#82ac7c",description:"0 cities"},
    JO:{name:"Jordan",color:"#bfd2c6",description:"0 cities"},
    JP:{name:"Japan",color:"#7297a0",description:"14 cities"},
    KZ:{name:"Kazakhstan",color:"#8d9daf",description:"0 cities"},
    KE:{name:"Kenya",color:"#b8d0cd",description:"0 cities"},
    KG:{name:"Kyrgyzstan",color:"#b48c8a",description:"0 cities"},
    KH:{name:"Cambodia",color:"#d0b1a3",description:"0 cities"},
    KR:{name:"Republic of Korea",color:"#a88c7d",description:"5 cities"},
    XK:{name:"Kosovo",color:"#a493b7",description:"0 cities"},
    KW:{name:"Kuwait",color:"#a089a0",description:"0 cities"},
    LA:{name:"Lao PDR",color:"#6d6e80",description:"0 cities"},
    LB:{name:"Lebanon",color:"#e9dcc9",description:"0 cities"},
    LR:{name:"Liberia",color:"#cfbeb4",description:"0 cities"},
    LY:{name:"Libya",color:"#b1b6ba",description:"0 cities"},
    LK:{name:"Sri Lanka",color:"#82ac7c",description:"0 cities"},
    LS:{name:"Lesotho",color:"#bfd2c6",description:"0 cities"},
    LT:{name:"Lithuania",color:"#7297a0",description:"0 cities"},
    LU:{name:"Luxembourg",color:"#8d9daf",description:"0 cities"},
    LV:{name:"Latvia",color:"#b8d0cd",description:"0 cities"},
    MA:{name:"Morocco",color:"#b48c8a",description:"0 cities"},
    MD:{name:"Moldova",color:"#d0b1a3",description:"0 cities"},
    MG:{name:"Madagascar",color:"#a88c7d",description:"0 cities"},
    MX:{name:"Mexico",color:"#a493b7",description:"1 city"},
    MK:{name:"Macedonia",color:"#a089a0",description:"0 cities"},
    ML:{name:"Mali",color:"#6d6e80",description:"0 cities"},
    MM:{name:"Myanmar",color:"#e9dcc9",description:"0 cities"},
    ME:{name:"Montenegro",color:"#cfbeb4",description:"0 cities"},
    MN:{name:"Mongolia",color:"#b1b6ba",description:"0 cities"},
    MZ:{name:"Mozambique",color:"#82ac7c",description:"0 cities"},
    MR:{name:"Mauritania",color:"#bfd2c6",description:"0 cities"},
    MW:{name:"Malawi",color:"#7297a0",description:"0 cities"},
    MY:{name:"Malaysia",color:"#8d9daf",description:"1 city"},
    NA:{name:"Namibia",color:"#b8d0cd",description:"0 cities"},
    NE:{name:"Niger",color:"#b48c8a",description:"0 cities"},
    NG:{name:"Nigeria",color:"#d0b1a3",description:"0 cities"},
    NI:{name:"Nicaragua",color:"#a88c7d",description:"0 cities"},
    NL:{name:"Netherlands",color:"#a493b7",description:"0 cities"},
    NO:{name:"Norway",color:"#a089a0",description:"0 cities"},
    NP:{name:"Nepal",color:"#6d6e80",description:"0 cities"},
    NZ:{name:"New Zealand",color:"#e9dcc9",description:"2 cities"},
    OM:{name:"Oman",color:"#cfbeb4",description:"0 cities"},
    PK:{name:"Pakistan",color:"#b1b6ba",description:"0 cities"},
    PA:{name:"Panama",color:"#82ac7c",description:"0 cities"},
    PE:{name:"Peru",color:"#bfd2c6",description:"0 cities"},
    PH:{name:"Philippines",color:"#7297a0",description:"1 city"},
    PG:{name:"Papua New Guinea",color:"#8d9daf",description:"0 cities"},
    PL:{name:"Poland",color:"#b8d0cd",description:"0 cities"},
    KP:{name:"Dem. Rep. Korea",color:"#b48c8a",description:"0 cities"},
    PT:{name:"Portugal",color:"#d0b1a3",description:"1 city"},
    PY:{name:"Paraguay",color:"#a88c7d",description:"0 cities"},
    PS:{name:"Palestine",color:"#a493b7",description:"0 cities"},
    QA:{name:"Qatar",color:"#a089a0",description:"1 city"},
    RO:{name:"Romania",color:"#6d6e80",description:"0 cities"},
    RU:{name:"Russia",color:"#e9dcc9",description:"1 city"},
    RW:{name:"Rwanda",color:"#cfbeb4",description:"0 cities"},
    EH:{name:"Western Sahara",color:"#b1b6ba",description:"0 cities"},
    SA:{name:"Saudi Arabia",color:"#82ac7c",description:"0 cities"},
    SD:{name:"Sudan",color:"#bfd2c6",description:"0 cities"},
    SS:{name:"South Sudan",color:"#7297a0",description:"0 cities"},
    SN:{name:"Senegal",color:"#8d9daf",description:"0 cities"},
    SL:{name:"Sierra Leone",color:"#b8d0cd",description:"0 cities"},
    SV:{name:"El Salvador",color:"#b48c8a",description:"0 cities"},
    RS:{name:"Serbia",color:"#d0b1a3",description:"0 cities"},
    SR:{name:"Suriname",color:"#a88c7d",description:"0 cities"},
    SK:{name:"Slovakia",color:"#a493b7",description:"1 city"},
    SI:{name:"Slovenia",color:"#a089a0",description:"0 cities"},
    SE:{name:"Sweden",color:"#6d6e80",description:"0 cities"},
    SZ:{name:"Eswatini",color:"#e9dcc9",description:"0 cities"},
    SY:{name:"Syria",color:"#cfbeb4",description:"0 cities"},
    TD:{name:"Chad",color:"#b1b6ba",description:"0 cities"},
    TG:{name:"Togo",color:"#82ac7c",description:"0 cities"},
    TH:{name:"Thailand",color:"#bfd2c6",description:"1 city"},
    TJ:{name:"Tajikistan",color:"#7297a0",description:"0 cities"},
    TM:{name:"Turkmenistan",color:"#8d9daf",description:"0 cities"},
    TL:{name:"Timor-Leste",color:"#b8d0cd",description:"0 cities"},
    TN:{name:"Tunisia",color:"#b48c8a",description:"0 cities"},
    TR:{name:"Turkey",color:"#d0b1a3",description:"1 city"},
    TW:{name:"Taiwan",color:"#a88c7d",description:"3 cities"},
    TZ:{name:"Tanzania",color:"#a493b7",description:"0 cities"},
    UG:{name:"Uganda",color:"#a089a0",description:"0 cities"},
    UA:{name:"Ukraine",color:"#6d6e80",description:"0 cities"},
    UY:{name:"Uruguay",color:"#e9dcc9",description:"0 cities"},
    US:{name:"United States",color:"#cfbeb4",description:"33 cities"},
    UZ:{name:"Uzbekistan",color:"#b1b6ba",description:"0 cities"},
    VE:{name:"Venezuela",color:"#82ac7c",description:"0 cities"},
    VN:{name:"Vietnam",color:"#bfd2c6",description:"2 cities"},
    VU:{name:"Vanuatu",color:"#7297a0",description:"0 cities"},
    YE:{name:"Yemen",color:"#8d9daf",description:"0 cities"},
    ZA:{name:"South Africa",color:"#b8d0cd",description:"0 cities"},
    ZM:{name:"Zambia",color:"#b48c8a",description:"0 cities"},
    ZW:{name:"Zimbabwe",color:"#d0b1a3",description:"0 cities"},
    SO:{name:"Somalia",color:"#a88c7d",description:"0 cities"},
    GF:{name:"France",color:"#a493b7",description:"0 cities"},
    FR:{name:"France",color:"#a089a0",description:"2 cities"},
    ES:{name:"Spain",color:"#6d6e80",description:"1 city"},
    AW:{name:"Aruba",color:"#e9dcc9",description:"0 cities"},
    AI:{name:"Anguilla",color:"#cfbeb4",description:"0 cities"},
    AD:{name:"Andorra",color:"#b1b6ba",description:"0 cities"},
    AG:{name:"Antigua and Barbuda",color:"#82ac7c",description:"0 cities"},
    BS:{name:"Bahamas",color:"#bfd2c6",description:"0 cities"},
    BM:{name:"Bermuda",color:"#7297a0",description:"0 cities"},
    BB:{name:"Barbados",color:"#8d9daf",description:"0 cities"},
    KM:{name:"Comoros",color:"#b8d0cd",description:"0 cities"},
    CV:{name:"Cape Verde",color:"#b48c8a",description:"0 cities"},
    KY:{name:"Cayman Islands",color:"#d0b1a3",description:"0 cities"},
    DM:{name:"Dominica",color:"#a88c7d",description:"0 cities"},
    FK:{name:"Falkland Islands",color:"#a493b7",description:"0 cities"},
    FO:{name:"Faeroe Islands",color:"#a089a0",description:"0 cities"},
    GD:{name:"Grenada",color:"#6d6e80",description:"0 cities"},
    HK:{name:"Hong Kong",color:"#e9dcc9",description:"0 cities"},
    KN:{name:"Saint Kitts and Nevis",color:"#cfbeb4",description:"0 cities"},
    LC:{name:"Saint Lucia",color:"#b1b6ba",description:"0 cities"},
    LI:{name:"Liechtenstein",color:"#82ac7c",description:"0 cities"},
    MF:{name:"Saint Martin (French)",color:"#bfd2c6",description:"0 cities"},
    MV:{name:"Maldives",color:"#7297a0",description:"0 cities"},
    MT:{name:"Malta",color:"#8d9daf",description:"0 cities"},
    MS:{name:"Montserrat",color:"#b8d0cd",description:"0 cities"},
    MU:{name:"Mauritius",color:"#b48c8a",description:"1 city"},
    NC:{name:"New Caledonia",color:"#d0b1a3",description:"0 cities"},
    NR:{name:"Nauru",color:"#a88c7d",description:"0 cities"},
    PN:{name:"Pitcairn Islands",color:"#a493b7",description:"0 cities"},
    PR:{name:"Puerto Rico",color:"#a089a0",description:"0 cities"},
    PF:{name:"French Polynesia",color:"#6d6e80",description:"0 cities"},
    SG:{name:"Singapore",color:"#e9dcc9",description:"1 city"},
    SB:{name:"Solomon Islands",color:"#cfbeb4",description:"0 cities"},
    ST:{name:"São Tomé and Principe",color:"#b1b6ba",description:"0 cities"},
    SX:{name:"Saint Martin (Dutch)",color:"#82ac7c",description:"0 cities"},
    SC:{name:"Seychelles",color:"#bfd2c6",description:"0 cities"},
    TC:{name:"Turks and Caicos Islands",color:"#7297a0",description:"0 cities"},
    TO:{name:"Tonga",color:"#8d9daf",description:"0 cities"},
    TT:{name:"Trinidad and Tobago",color:"#b8d0cd",description:"0 cities"},
    VC:{name:"Saint Vincent and the Grenadines",color:"#b48c8a",description:"0 cities"},
    VG:{name:"British Virgin Islands",color:"#d0b1a3",description:"0 cities"},
    VI:{name:"United States Virgin Islands",color:"#a88c7d",description:"0 cities"},
    CY:{name:"Cyprus",color:"#a493b7",description:"0 cities"},
    RE:{name:"Reunion (France)",color:"#a089a0",description:"0 cities"},
    YT:{name:"Mayotte (France)",color:"#6d6e80",description:"0 cities"},
    MQ:{name:"Martinique (France)",color:"#e9dcc9",description:"0 cities"},
    GP:{name:"Guadeloupe (France)",color:"#cfbeb4",description:"0 cities"},
    CW:{name:"Curaco (Netherlands)",color:"#b1b6ba",description:"0 cities"},
    IC:{name:"Canary Islands (Spain)",color:"#82ac7c",description:"0 cities"}
  },
  locations: {
    // ══════════════ ASIA ══════════════
    // China
    "0":  {name:"Beijing",          lat:39.9042,  lng:116.4074, url:"https://www.metliner.com/maps/asia/beijing",           description:"Beijing, China"},
    "1":  {name:"Chongqing",        lat:29.5630,  lng:106.5516, url:"https://www.metliner.com/maps/asia/chongqing",         description:"Chongqing, China"},
    "2":  {name:"Dongguan",         lat:23.0207,  lng:113.7518, url:"https://www.metliner.com/maps/asia/dongguan",          description:"Dongguan, China"},
    "3":  {name:"Guangzhou",        lat:23.1291,  lng:113.2644, url:"https://www.metliner.com/maps/asia/guangzhou",         description:"Guangzhou, China"},
    "4":  {name:"Harbin",           lat:45.8038,  lng:126.5350, url:"https://www.metliner.com/maps/asia/harbin",            description:"Harbin, China"},
    "5":  {name:"Hong Kong",        lat:22.3193,  lng:114.1694, url:"https://www.metliner.com/maps/asia/hong-kong",         description:"Hong Kong, China"},
    "6":  {name:"Macau",            lat:22.1987,  lng:113.5439, url:"https://www.metliner.com/maps/asia/macau",             description:"Macau, China"},
    "7":  {name:"Shenzhen",         lat:22.5431,  lng:114.0579, url:"https://www.metliner.com/maps/asia/shenzhen",          description:"Shenzhen, China"},
    "8":  {name:"Xiamen",           lat:24.4798,  lng:118.0894, url:"https://www.metliner.com/maps/asia/xiamen",            description:"Xiamen, China"},
    // Indonesia
    "9":  {name:"Palembang",        lat:-2.9761,  lng:104.7754, url:"https://www.metliner.com/maps/asia/palembang",         description:"Palembang, Indonesia"},
    // Japan
    "10": {name:"Fukuoka",          lat:33.5904,  lng:130.4017, url:"https://www.metliner.com/maps/asia/fukuoka",           description:"Fukuoka, Japan"},
    "11": {name:"Hakodate",         lat:41.7688,  lng:140.7290, url:"https://www.metliner.com/maps/asia/hakodate",          description:"Hakodate, Japan"},
    "12": {name:"Hiroshima",        lat:34.3853,  lng:132.4553, url:"https://www.metliner.com/maps/asia/hiroshima",         description:"Hiroshima, Japan"},
    "13": {name:"Kagoshima",        lat:31.5966,  lng:130.5571, url:"https://www.metliner.com/maps/asia/kagoshima",         description:"Kagoshima, Japan"},
    "14": {name:"Nagano",           lat:36.6485,  lng:138.1947, url:"https://www.metliner.com/maps/asia/nagano",            description:"Nagano, Japan"},
    "15": {name:"Nagasaki",         lat:32.7503,  lng:129.8777, url:"https://www.metliner.com/maps/asia/nagasaki",          description:"Nagasaki, Japan"},
    "16": {name:"Nagoya",           lat:35.1815,  lng:136.9066, url:"https://www.metliner.com/maps/asia/nagoya",            description:"Nagoya, Japan"},
    "17": {name:"Naha",             lat:26.2124,  lng:127.6792, url:"https://www.metliner.com/maps/asia/naha",              description:"Naha, Japan"},
    "18": {name:"Niigata",          lat:37.9026,  lng:139.0232, url:"https://www.metliner.com/maps/asia/niigata",           description:"Niigata, Japan"},
    "19": {name:"Okayama",          lat:34.6551,  lng:133.9195, url:"https://www.metliner.com/maps/asia/okayama",           description:"Okayama, Japan"},
    "20": {name:"Osaka",            lat:34.6937,  lng:135.5023, url:"https://www.metliner.com/maps/asia/osaka",             description:"Osaka, Japan"},
    "21": {name:"Sapporo",          lat:43.0618,  lng:141.3545, url:"https://www.metliner.com/maps/asia/sapporo",           description:"Sapporo, Japan"},
    "22": {name:"Sendai",           lat:38.2682,  lng:140.8694, url:"https://www.metliner.com/maps/asia/sendai",            description:"Sendai, Japan"},
    "23": {name:"Tokyo",            lat:35.6762,  lng:139.6503, url:"https://www.metliner.com/maps/asia/tokyo",             description:"Tokyo, Japan"},
    // Malaysia
    "24": {name:"Kuala Lumpur",     lat:3.1390,   lng:101.6869, url:"https://www.metliner.com/maps/asia/kuala-lumpur",      description:"Kuala Lumpur, Malaysia"},
    // Philippines
    "25": {name:"Manila",           lat:14.5995,  lng:120.9842, url:"https://www.metliner.com/maps/asia/manila",            description:"Manila, Philippines"},
    // Qatar
    "26": {name:"Doha",             lat:25.2854,  lng:51.5310,  url:"https://www.metliner.com/maps/asia/doha",              description:"Doha, Qatar"},
    // Singapore
    "27": {name:"Singapore",        lat:1.3521,   lng:103.8198, url:"https://www.metliner.com/maps/asia/singapore",         description:"Singapore"},
    // South Korea
    "28": {name:"Busan",            lat:35.1796,  lng:129.0756, url:"https://www.metliner.com/maps/asia/busan",             description:"Busan, South Korea"},
    "29": {name:"Daegu",            lat:35.8714,  lng:128.6014, url:"https://www.metliner.com/maps/asia/daegu",             description:"Daegu, South Korea"},
    "30": {name:"Daejeon",          lat:36.3504,  lng:127.3845, url:"https://www.metliner.com/maps/asia/daejeon",           description:"Daejeon, South Korea"},
    "31": {name:"Gwangju",          lat:35.1595,  lng:126.8526, url:"https://www.metliner.com/maps/asia/gwangju",           description:"Gwangju, South Korea"},
    "32": {name:"Seoul",            lat:37.5665,  lng:126.9780, url:"https://www.metliner.com/maps/asia/seoul",             description:"Seoul, South Korea"},
    // Taiwan
    "33": {name:"Kaohsiung",        lat:22.6273,  lng:120.3014, url:"https://www.metliner.com/maps/asia/kaohsiung",         description:"Kaohsiung, Taiwan"},
    "34": {name:"Taichung",         lat:24.1477,  lng:120.6736, url:"https://www.metliner.com/maps/asia/taichung",          description:"Taichung, Taiwan"},
    "35": {name:"Taipei",           lat:25.0330,  lng:121.5654, url:"https://www.metliner.com/maps/asia/taipei",            description:"Taipei, Taiwan"},
    // Thailand
    "36": {name:"Bangkok",          lat:13.7563,  lng:100.5018, url:"https://www.metliner.com/maps/asia/bangkok",           description:"Bangkok, Thailand"},
    // UAE
    "37": {name:"Dubai",            lat:25.2048,  lng:55.2708,  url:"https://www.metliner.com/maps/asia/dubai",             description:"Dubai, UAE"},
    // Vietnam
    "38": {name:"Hanoi",            lat:21.0285,  lng:105.8542, url:"https://www.metliner.com/maps/asia/hanoi",             description:"Hanoi, Vietnam"},
    "39": {name:"Ho Chi Minh City", lat:10.8231,  lng:106.6297, url:"https://www.metliner.com/maps/asia/ho-chi-minh-city",  description:"Ho Chi Minh City, Vietnam"},

    // ══════════════ OCEANIA ══════════════
    "40": {name:"Sydney",           lat:-33.8688, lng:151.2093, url:"https://www.metliner.com/maps/oceania/sydney",         description:"Sydney, Australia"},
    "41": {name:"Melbourne",        lat:-37.8136, lng:144.9631, url:"https://www.metliner.com/maps/oceania/melbourne",      description:"Melbourne, Australia"},
    "42": {name:"Auckland",         lat:-36.8485, lng:174.7633, url:"https://www.metliner.com/maps/oceania/auckland",       description:"Auckland, New Zealand"},
    "43": {name:"Wellington",       lat:-41.2865, lng:174.7762, url:"https://www.metliner.com/maps/oceania/wellington",     description:"Wellington, New Zealand"},

    // ══════════════ EUROPE ══════════════
    "44": {name:"Vienna",           lat:48.2082,  lng:16.3738,  url:"https://www.metliner.com/maps/europe/vienna",          description:"Vienna, Austria"},
    "45": {name:"Copenhagen",       lat:55.6761,  lng:12.5683,  url:"https://www.metliner.com/maps/europe/copenhagen",      description:"Copenhagen, Denmark"},
    "46": {name:"Lille",            lat:50.6292,  lng:3.0573,   url:"https://www.metliner.com/maps/europe/lille",           description:"Lille, France"},
    "47": {name:"Paris",            lat:48.8566,  lng:2.3522,   url:"https://www.metliner.com/maps/europe/paris",           description:"Paris, France"},
    "48": {name:"Berlin",           lat:52.5200,  lng:13.4050,  url:"https://www.metliner.com/maps/europe/berlin",          description:"Berlin, Germany"},
    "49": {name:"Lisbon",           lat:38.7169,  lng:-9.1395,  url:"https://www.metliner.com/maps/europe/lisbon",          description:"Lisbon, Portugal"},
    "50": {name:"Moscow",           lat:55.7558,  lng:37.6176,  url:"https://www.metliner.com/maps/europe/moscow",          description:"Moscow, Russia"},
    "51": {name:"Bratislava",       lat:48.1486,  lng:17.1077,  url:"https://www.metliner.com/maps/europe/bratislava",      description:"Bratislava, Slovakia"},
    "52": {name:"Madrid",           lat:40.4168,  lng:-3.7038,  url:"https://www.metliner.com/maps/europe/madrid",          description:"Madrid, Spain"},
    "53": {name:"Istanbul",         lat:41.0082,  lng:28.9784,  url:"https://www.metliner.com/maps/europe/istanbul",        description:"Istanbul, Turkey"},
    "54": {name:"London",           lat:51.5074,  lng:-0.1278,  url:"https://www.metliner.com/maps/europe/london",          description:"London, United Kingdom"},

    // ══════════════ AFRICA ══════════════
    "55": {name:"Port Louis",       lat:-20.1609, lng:57.4961,  url:"https://www.metliner.com/maps/africa/port-louis",      description:"Port Louis, Mauritius"},

    // ══════════════ AMERICAS ══════════════
    // Brazil
    "56": {name:"São Paulo",        lat:-23.5505, lng:-46.6333, url:"https://www.metliner.com/maps/america/sao-paulo",      description:"São Paulo, Brazil"},
    // Canada
    "57": {name:"Edmonton",         lat:53.5461,  lng:-113.4938,url:"https://www.metliner.com/maps/america/edmonton",       description:"Edmonton, Canada"},
    "58": {name:"Calgary",          lat:51.0447,  lng:-114.0719,url:"https://www.metliner.com/maps/america/calgary",        description:"Calgary, Canada"},
    "59": {name:"Montreal",         lat:45.5017,  lng:-73.5673, url:"https://www.metliner.com/maps/america/montreal",       description:"Montreal, Canada"},
    "60": {name:"Ottawa",           lat:45.4215,  lng:-75.6972, url:"https://www.metliner.com/maps/america/ottawa",         description:"Ottawa, Canada"},
    "61": {name:"Toronto",          lat:43.6532,  lng:-79.3832, url:"https://www.metliner.com/maps/america/toronto",        description:"Toronto, Canada"},
    "62": {name:"Vancouver",        lat:49.2827,  lng:-123.1207,url:"https://www.metliner.com/maps/america/vancouver",      description:"Vancouver, Canada"},
    // Mexico
    "63": {name:"Mexico City",      lat:19.4326,  lng:-99.1332, url:"https://www.metliner.com/maps/america/mexico-city",    description:"Mexico City, Mexico"},
    // USA
    "64": {name:"Albuquerque",      lat:35.0844,  lng:-106.6504,url:"https://www.metliner.com/maps/america/albuquerque",    description:"Albuquerque, USA"},
    "65": {name:"Atlanta",          lat:33.7490,  lng:-84.3880, url:"https://www.metliner.com/maps/america/atlanta",        description:"Atlanta, USA"},
    "66": {name:"Austin",           lat:30.2672,  lng:-97.7431, url:"https://www.metliner.com/maps/america/austin",         description:"Austin, USA"},
    "67": {name:"Boston",           lat:42.3601,  lng:-71.0589, url:"https://www.metliner.com/maps/america/boston",         description:"Boston, USA"},
    "68": {name:"Buffalo",          lat:42.8864,  lng:-78.8784, url:"https://www.metliner.com/maps/america/buffalo",        description:"Buffalo, USA"},
    "69": {name:"Charlotte",        lat:35.2271,  lng:-80.8431, url:"https://www.metliner.com/maps/america/charlotte",      description:"Charlotte, USA"},
    "70": {name:"Cincinnati",       lat:39.1031,  lng:-84.5120, url:"https://www.metliner.com/maps/america/cincinnati",     description:"Cincinnati, USA"},
    "71": {name:"Cleveland",        lat:41.4993,  lng:-81.6944, url:"https://www.metliner.com/maps/america/cleveland",      description:"Cleveland, USA"},
    "72": {name:"Dallas",           lat:32.7767,  lng:-96.7970, url:"https://www.metliner.com/maps/america/dallas",         description:"Dallas, USA"},
    "73": {name:"Denver",           lat:39.7392,  lng:-104.9903,url:"https://www.metliner.com/maps/america/denver",         description:"Denver, USA"},
    "74": {name:"Detroit",          lat:42.3314,  lng:-83.0458, url:"https://www.metliner.com/maps/america/detroit",        description:"Detroit, USA"},
    "75": {name:"El Paso",          lat:31.7619,  lng:-106.4850,url:"https://www.metliner.com/maps/america/el-paso",        description:"El Paso, USA"},
    "76": {name:"Honolulu",         lat:21.3069,  lng:-157.8583,url:"https://www.metliner.com/maps/america/honolulu",       description:"Honolulu, USA"},
    "77": {name:"Jacksonville",     lat:30.3322,  lng:-81.6557, url:"https://www.metliner.com/maps/america/jacksonville",   description:"Jacksonville, USA"},
    "78": {name:"Kansas City",      lat:39.0997,  lng:-94.5786, url:"https://www.metliner.com/maps/america/kansas-city",    description:"Kansas City, USA"},
    "79": {name:"Las Vegas",        lat:36.1699,  lng:-115.1398,url:"https://www.metliner.com/maps/america/las-vegas",      description:"Las Vegas, USA"},
    "80": {name:"Little Rock",      lat:34.7465,  lng:-92.2896, url:"https://www.metliner.com/maps/america/little-rock",    description:"Little Rock, USA"},
    "81": {name:"Los Angeles",      lat:34.0522,  lng:-118.2437,url:"https://www.metliner.com/maps/america/los-angeles",    description:"Los Angeles, USA"},
    "82": {name:"Miami",            lat:25.7617,  lng:-80.1918, url:"https://www.metliner.com/maps/america/miami",          description:"Miami, USA"},
    "83": {name:"Nashville",        lat:36.1627,  lng:-86.7816, url:"https://www.metliner.com/maps/america/nashville",      description:"Nashville, USA"},
    "84": {name:"Norfolk",          lat:36.8508,  lng:-76.2859, url:"https://www.metliner.com/maps/america/norfolk",        description:"Norfolk, USA"},
    "85": {name:"Oklahoma City",    lat:35.4676,  lng:-97.5164, url:"https://www.metliner.com/maps/america/oklahoma-city",  description:"Oklahoma City, USA"},
    "86": {name:"Orlando",          lat:28.5383,  lng:-81.3792, url:"https://www.metliner.com/maps/america/orlando",        description:"Orlando, USA"},
    "87": {name:"Phoenix",          lat:33.4484,  lng:-112.0740,url:"https://www.metliner.com/maps/america/phoenix",        description:"Phoenix, USA"},
    "88": {name:"Pittsburgh",       lat:40.4406,  lng:-79.9959, url:"https://www.metliner.com/maps/america/pittsburgh",     description:"Pittsburgh, USA"},
    "89": {name:"Salt Lake City",   lat:40.7608,  lng:-111.8910,url:"https://www.metliner.com/maps/america/salt-lake-city", description:"Salt Lake City, USA"},
    "90": {name:"San Francisco",    lat:37.7749,  lng:-122.4194,url:"https://www.metliner.com/maps/america/san-francisco",  description:"San Francisco, USA"},
    "91": {name:"Seattle",          lat:47.6062,  lng:-122.3321,url:"https://www.metliner.com/maps/america/seattle",        description:"Seattle, USA"},
    "92": {name:"St. Louis",        lat:38.6270,  lng:-90.1994, url:"https://www.metliner.com/maps/america/st-louis",       description:"St. Louis, USA"},
    "93": {name:"Tampa",            lat:27.9506,  lng:-82.4572, url:"https://www.metliner.com/maps/america/tampa",          description:"Tampa, USA"},
    "94": {name:"Tucson",           lat:32.2226,  lng:-110.9747,url:"https://www.metliner.com/maps/america/tucson",         description:"Tucson, USA"}
  },
  labels: {},
  legend: {entries: []},
  regions: {
    "0": {name:"Oceania", states:["AU","FJ","GU","MH","NZ","PW","WS","SB","TK","PG"], color:"#ff0025"},
    "1": {name:"America", states:["AI","AR","AW","BB","BZ","BM","BO","BR","KY","CL","CO","CR","PA","PY","PE","KN","DO","DM","EC","SV","GD","GT","GY","HA","HN","JM","LC","VC","SR","TT","UY","VE","NI","CU","HT","AG","GF","US","MX","CA","BS","PR"], color:"#ee334e"},
    "2": {name:"Europe",  states:["AL","AD","AT","BY","BE","BA","BV","BG","HR","CY","CZ","DK","EE","FO","FK","FI","FR","TF","DE","GI","GR","GL","GG","VA","HU","IS","IE","IM","IT","JE","LV","LI","LT","LU","MK","MT","MD","MC","NL","NO","PL","PT","RO","RU","SM","RS","ME","XK","SK","SI","ES","SJ","SE","CH","UA","GB","TR"], color:"#0081c8"},
    "3": {name:"Africa",  states:["DZ","AO","BJ","BW","BF","BI","CM","CV","CF","TD","CG","CI","MG","MW","ML","MU","MR","MA","NA","NE","NG","CD","EG","ER","ET","GA","GH","GN","LS","ST","SN","SC","SL","SO","ZA","SZ","TZ","TG","TN","UG","ZM","ZW","LY","SD","SS","KE","MZ","RW","LR","GW","EH"], color:"#000000"},
    "5": {name:"Asia",    states:["AF","AM","AZ","BH","BD","BT","BN","KH","CN","TL","GE","HK","IN","ID","IR","IQ","IL","JP","JO","KZ","KP","KR","KW","KG","LA","LB","MO","MY","MN","MM","NP","OM","PK","PH","QA","SA","SG","LK","SY","TW","TJ","TH","TM","AE","UZ","VN","YE"], color:"#fcb131"}
  }
};
